name = "habitica-bot-dev"
type = "webpack"
account_id = "18d539553f6adb73c3dc0efa2824280d"
workers_dev = true
vars = { ENVIRONMENT = "dev" }

[env.production]
name = "habitica-bot"
workers_dev = true
vars = { ENVIRONMENT = "production" }