name = "habitica-bot-dev"
type = "webpack"
account_id = "18d539553f6adb73c3dc0efa2824280d"
workers_dev = true
vars = { ENVIRONMENT = "dev" }
webpack_config = "webpack.config.js"

[env.production]
name = "habitica-bot"
workers_dev = true
vars = { ENVIRONMENT = "production" }


[env.test]
name = "habitica-bot-test"
workers_dev = true
vars = { ENVIRONMENT = "test" }